package:
  name: fintools
  version: "0.2.2"

source:
  git_rev: "0.2.2"
  git_url: https://github.com/scubamut/fintools.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - fintools

about:
  home: https://github.com/scubamut/fintools
  license: MIT
  license_file: LICENSE
